// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChripByID = `-- name: DeleteChripByID :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChripByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChripByID, id)
	return err
}
